### ISSUE TITLE
Attach JR East full Shinkansen and Mini-Shinkansen

### ISSUE THREAD

**Issue by sjcl** [KeepinItRail/JPplusShinkansen#1]
Is it technically difficult?

Many trains like Yamabiko/Tsubasa between Tokyo and Fukushima and Hayabusa/Komachi between Tokyo and Morioka operate with a Mini-Shinkansen attached to a full Shinkansen.
I'd be happy to do that in the game🙂

**Comment by KeepinItRail** [comment]
I tried E5/H5 + E6 sets, but they were pretty glitchy first time round so I stripped them back out. 🤦‍♂️

I then prevented Full and Minis from being joined together at all since, of course people will try and couple them and then no doubt see weird things happen -> bug reports. 

Think there might be another way which I'll give a go when I get a chance.

**Comment by sjcl** [comment]
That makes sense, thank you for taking the time.
Hope another way will work out 🙏

**Comment by KeepinItRail** [comment]
This is the E5 (10/8) + E6 coupling 'horizontal gap'. Look at 12/8 to see which template needs to shift

![Screenshot from 2023-11-11 04-19-52](https://github.com/KeepinItRail/JPplusShinkansen/assets/74462886/9bccac2c-3920-413c-8eff-448d6b437918)

**Comment by KeepinItRail** [comment]
![Screenshot from 2023-11-12 07-45-56](https://github.com/KeepinItRail/JPplusShinkansen/assets/74462886/6c963fc4-2c58-4d3d-beae-3233c10dd3ff)

**Comment by KeepinItRail** [comment]
Starting to get somewhere! :smile: 

Need to sort out the cornering

![Screenshot from 2023-11-19 15-25-58](https://github.com/KeepinItRail/JPplusShinkansen/assets/74462886/b9e5e281-df21-4420-848c-25c6cd992372)

![Screenshot from 2023-11-19 15-49-02](https://github.com/KeepinItRail/JPplusShinkansen/assets/74462886/ceb8883a-d835-46d3-b1c8-4cab1e0c28ce)

![Screenshot from 2023-11-19 15-49-11](https://github.com/KeepinItRail/JPplusShinkansen/assets/74462886/05591bc8-9497-454b-97ca-39124e8c1354)

![Screenshot from 2023-11-19 15-49-20](https://github.com/KeepinItRail/JPplusShinkansen/assets/74462886/47887cc4-46f8-4b8a-a5ea-a258d3039abe)

**Comment by KeepinItRail** [comment]
E5 and E6 coupling released in v0.50
