### ISSUE TITLE
pantograph issue

### ISSUE THREAD

**Issue by diaodiaotaoge** [KeepinItRail/JPplusShinkansen#13]
the N700s only have one pantograph
It should have two pantographs since the formation of six cars(match with Kamome Livery)
And the 800 Series also has the same problem
![Campbell   Co ，2025-10-09](https://github.com/KeepinItRail/JPplusShinkansen/assets/171007280/1ce4c70b-1927-405d-a191-bb17318c0612)

**Comment by KeepinItRail** [comment]
Thanks for this. 
- 800 Series code changed to start the 2nd panto from 6 car lengths (as opposed to 8)
- N700S was pulling coach sprite for the 2nd panto car instead of the panto sprite. Fixed

Will be fixed in the next release
