### ISSUE TITLE
Sprites Error of e5&e6

### ISSUE THREAD

**Issue by Babel-TTT** [KeepinItRail/JPplusShinkansen#14]
when the time use 10/8 length Shinkansen , JP3 SHikansen removel was on,  sprites of the long E5&E6 (12 tlies) will be mistaken.
like the image
![QQ图片20240611012941](https://github.com/KeepinItRail/JPplusShinkansen/assets/155768169/9d8310db-4c09-4dc3-90c5-a14dae0c54f4)
![QQ图片20240611012950](https://github.com/KeepinItRail/JPplusShinkansen/assets/155768169/42f6516f-42d9-4005-8c84-22df01c84b37)
(the question mark is not a cursor)

**Comment by KeepinItRail** [comment]
Hmm. I'm not able to replicate this. What version are you using?

Would you be able to pass me a .sav file with ths issue and I can take a look?

**Comment by Babel-TTT** [comment]
OK ,I played with jgrpp 0.58.1
the .sav here
[err.zip](https://github.com/user-attachments/files/15787865/err.zip)

**Comment by KeepinItRail** [comment]
Getting the same issue as you with this save. Suspect it might be a clash with another grf. Will see if it's that.

For reference
![Screenshot from 2024-06-12 06-52-09](https://github.com/KeepinItRail/JPplusShinkansen/assets/74462886/2973977a-b8c5-41b0-ae87-3a77378566a1)

Adding the same grf (albeit new versions for Shinkansen) doesn't get the error
![image](https://github.com/KeepinItRail/JPplusShinkansen/assets/74462886/74cb206c-a19a-4f2b-81cc-c6694ea59785)

**Comment by Babel-TTT** [comment]
I'm sorry that but it still dont work in 0.5.1  :(
<img width="1277" alt="屏幕截图 2024-06-13 145953" src="https://github.com/KeepinItRail/JPplusShinkansen/assets/155768169/3928c085-4653-417e-bf5a-d7be87565b41">
[err.zip](https://github.com/user-attachments/files/15815194/err.zip)

**Comment by KeepinItRail** [comment]
Recoded how E5 and E6 coupling works
