### ISSUE TITLE
 Another pantograph issue

### ISSUE THREAD

**Issue by diaodiaotaoge** [KeepinItRail/JPplusShinkansen#16]
I download  the v0.51 and found a issue, the 6cars set N700S only have one pantograph, which is does not match the reality of N700S-8000.
![Bigwig   Co ，2030-03-23](https://github.com/user-attachments/assets/b508e382-22f6-40f9-a760-f6a96cd3d6b7)
![N700S-8000](https://github.com/user-attachments/assets/da933c62-db13-41b4-a2c3-926a08753458)

**Comment by KeepinItRail** [comment]
Thanks for reporting this. Will update for this in a future version.

**Comment by KeepinItRail** [comment]
Updated for next release
