### ISSUE TITLE
Running Costs are Too Low for Full Shinkansen

### ISSUE THREAD

**Issue by GrandAdmiralUehara** [KeepinItRail/JPplusShinkansen#2]
The most recent update appears to have skewed the running costs for the full Shinkansen to be too low, especially when compared to the mini-Shinkansen. Full Shinkansen appear to have appropriate running costs in the buy menu, but actually buying one and checking the running costs for the purchased train reveals that they are actually much lower, likely due to a modifier of some kind.

**Comment by KeepinItRail** [comment]
Thanks for this. I noticed some things changed how they were calculated when the set shifted from the fixed to variable length sets. Not this one though. There is a useful feature to allow the purchase menu to say something different from the calculated value, but this doesn't help much when you want to see the actual cost.

Will update this, likely after next weekend, hopefully to something more sensible.

**Comment by KeepinItRail** [comment]
Bumped up the costs and Full and Minis should be broadly in line now
