### ISSUE TITLE
Can't find E7 in Purchase Mune

### ISSUE THREAD

**Issue by Babel-TTT** [KeepinItRail/JPplusShinkansen#23]
![image](https://github.com/user-attachments/assets/b34daa3a-3421-4010-b45f-1dc1b12f660b)

this is the NewGRF list
![屏幕截图 2024-12-18 163802](https://github.com/user-attachments/assets/8329768a-f8dc-423e-aed8-bf4d165bfcc2)

But when I loaded JP+ Shinkensen after other train set 
It happend like [another issue I had reported](github.com/OpenTTD-JPplus/JPplusShinkansen/issues/14)
![image](https://github.com/user-attachments/assets/ef1f58d6-0ae4-4a9c-8987-ca581ed657eb)
![image](https://github.com/user-attachments/assets/3fd72689-362a-4b02-b0dc-676e73fc3fb8)

I dont know what it happened, but as my experience, Articulated part will stop working when Vehicle id > 16384 . Maybe it makes this wrong

**Comment by KeepinItRail** [comment]
Not getting this one, but modified the code slightly for the articulated parts of mucars to see if that resolves it for you. Could you try the grf in the repo to see if you still get that?

**Comment by Babel-TTT** [comment]
Not yet. But I found it can be solve by turn of the parameters "JapanSet3 Shinkansen removal".
